[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_stablecoin_standard = "C78Fk7ZeyGuQV92u3aKJQSeXMn35A9Jrjeyv33UNE4Nw"
sss_compliance_hook = "2fLexdN1nyTkWNcnagCSbVKUZ262d8WWAzeQUdjoEt88"

[programs.devnet]
solana_stablecoin_standard = "C78Fk7ZeyGuQV92u3aKJQSeXMn35A9Jrjeyv33UNE4Nw"
sss_compliance_hook = "2fLexdN1nyTkWNcnagCSbVKUZ262d8WWAzeQUdjoEt88"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
